audit_header: false
title: "Georgia's Best Real Estate Training"
description: -- CLIENT NAME --, a top Real Estate Agent in -- MARKET --, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Jim Casbarro
  title:
  license_number:
  about_markdown: |
    Hi, I’m Jim Casbarro. I am the CEO and founder of The GAFinestHomes Group, LLC with Keller Williams Realty. Ever since my first lemonade stand as a little kid I've had the entrepreneur bug. As I got older I knew I wanted to help people, and real estate was always interesting to me - it's one of the foundational needs of being a human. Being raised in an environment where I grew up in a loving home, coupled with the awesome wealth-building power of real estate, I couldn't help but learn as much as I could about the real estate industry.

    During my college years I discovered that real estate really was my passion and my calling. After graduating with a Bachelors in marketing, I took off to create my own investing and residential real estate business. After 6 amazing years in Georgia, the GAFinestHomes Group is that real estate business I envisioned when I was younger. Now I'm able to put all my knowledge and experience, along with the amazing people on our team, to work in the real estate realm for our clients.

    I focus on helping sellers market their home for maximum returns in the time frame they want, finding buyers the best home that matches their wishes, and maximizing our investors returns. Real Estate is my passion and calling and I would be honored to have the opportunity to share my knowledge and experience with you by learning your own real estate goals. Whether it's selling fast, selling for top dollar to make another move, looking to build wealth through investing, or practically anything else real-estate related, I'm eager to learn about what your real estate-related goals are to help make them a reality!
  market: Georgia
  brand: GAFinestHomes Group, LLC
  brokerage: Village Realty
  address: 2651 Dallas Hwy, Marietta GA 30064
  phone: 678-909-1783
  phone_type:
  phone2:
  phone2_type:
  email: Jim@GAFinestHomes.com
  url: GAFinestHomes.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how -- CLIENT BRAND -- can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/GAFinestHomesGroup/
  linkedin_url: https://www.linkedin.com/in/jimcasbarro/
  youtube_url: https://www.youtube.com/channel/UCt4spNH7Onco8pCA9IP3E9A?view_as=subscriber
  twitter_url: https://twitter.com/GAFinestHomes
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#3A9BC9'
  theme_color: '#143157'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
